name: Deploy Eidos

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: [self-hosted, gaia]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Log in to Registry
        uses: docker/login-action@v3
        with:
          registry: registry.tienzo.net
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_RAW_PASSWORD }}

      - name: Setup Secrets
        env:
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        run: |
          chmod +x scripts/ensure_secret.sh
          echo "EIDOS_POSTGRES_PASSWORD_NAME=$(echo "$POSTGRES_PASSWORD" | ./scripts/ensure_secret.sh eidos_postgres_password)" >> $GITHUB_ENV

      - name: Initialize Server Directories
        env:
          EIDOS_DB_MOUNT_PATH: ${{ vars.EIDOS_DB_MOUNT_PATH }}
        run: |
          chmod +x init-server.sh
          ./init-server.sh

      - name: Build and Deploy with Docker Compose
        env:
          REGISTRY_PREFIX: ${{ vars.REGISTRY_PREFIX }}
          EIDOS_DB_MOUNT_PATH: ${{ vars.EIDOS_DB_MOUNT_PATH }}
        run: |
          chmod +x scripts/deploy.sh
          ./scripts/deploy.sh "eidos" docker-compose.yml
